### PR TITLE
Minor namespace and warning changes

### PR DESCRIPTION
**Pull request by SloopyNoSleep**
I believe that none of my changes conflict with (ie rely on nice-to-haves from later) language version, but worth keeping in mind.

### CODE REVIEW

**Comment by Ashiepaws** [comment]
Thanks a lot for the "cleanup" changes with unused using directives and such, greatly appreciated. :)

I was thinking that there'd be a more elegant way of going about converting all the ItemData types, but I'm a little unclear on how your solution actually works. Might have to do with a bit of lack of in-depth C# knowledge, but would you mind explaining a bit? Specifically how `ItemUtil` actually ends up interfacing with the rest of your serialization classes.

**Comment by SloopyNoSleep** [comment]
> Thanks a lot for the "cleanup" changes with unused using directives and such, greatly appreciated. :)
> 
> I was thinking that there'd be a more elegant way of going about converting all the ItemData types, but I'm a little unclear on how your solution actually works. Might have to do with a bit of lack of in-depth C# knowledge, but would you mind explaining a bit? Specifically how `ItemUtil` actually ends up interfacing with the rest of your serialization classes.

Whoops, that commit was actually not supposed to make it into this PR. It is part of my other PR #8 which also has a stab at integration with ItemUtil.

**Comment by SloopyNoSleep** [comment]
I should be more careful as I'm typing away late at night... 😅

**Comment by Ashiepaws** [comment]
Haha, no worries :)

**Pull request merged**
